* 2. Explaining Consciousness

** 1. PANDORA'S BOX: SHOULD CONSCIOUSNESS BE DEMYSTIFIED?

He starts chattering about how we now understand things which previously were baffling mysteries, as consciousness is now. He tries to clear up the idea that, as some think (or even hope), consciousness is an unsolvable mystery. He keeps on going disecting whether it would be good or not to unravel what consciousness is. Would we loose something in the process? He believes that even in that case, the theoretical and moral gains from a good theory of consciousness would be worth it.

But would we really loose something if we come to understand consciousness? The author argues that there are some phenomena whose experience depends on the concept we have of them, and uses love as an example. The way we experience it is radically different when we are younger, and have a simpler idea of love. The way society experiences it has as well changed over time, as it has became more sofisticated. He exemplifies as well on money, whose very nature depends solely on the concept we have of it.

On the view of consciousness that Denet develops in this book, consciousness seems to be one of such concepts that depends largely on its associated concepts. If consciousness comes to be reduced to "mere matter in motion", what would happen to the concepts of "right" and "wrong", to our sense of moral and free will? He holds that his vision of consciousness would not dismiss such things. He ends up highlighting how when we solve a mystery, not only wonder does not disappear, but instead we find new beauties and complexities which can marvel us way more than the initial mystery.

** 2. THE MYSTERY OF CONSCIOUSNESS

We are able to experience complex sensory phenomena, which in turn elicit complex emotional phenomena. And we are even able to reflect on such sensory and emotional events. How can all that be just brain happenings? It seems as though they are something else, caused by brain happenings but made of different stuff, in a different space.

** 3. THE ATTRACTIONS OF MIND STUFF

When we do imagine something, what is this imagination made of? Assuming we are able to analyze the brain and discern what the person is thinking about, the question would remain: what in your brain is purple when you imagine a purple cow? The neurotransmiters, the neural arrangements and patterns of activations... "None of those properties *is* the very property of the cow in your imagination". Since you imagined a purple cow, something somewhere must have had the properties of that cow at that time. This imagined cow must be rendered not in the medium of brain stuff, but in the medium of *mind stuff*.

What properties does mind stuff have? The most obvious of it is that it *always has a witness*. Brain events are not witnessed, and it does not really matter whether they are or not. As any event in our stomach, they will happen either if there is an observer or not. Events in consciousness, however, are *by definition* witnessed, since there is always an *"experiencer"* experiencing them.

A question arises then: what is the *experiencer*? There seems to be no part of the brain which is the *thinker* or the *feeler*. When we think, is it our brain that thinks? Is it ourselves who think *with* our brain? Is there any difference? This idea of *self* distinct from the brain or body is deeply rooted in our way of thinking. If this is the case, such self must be made of mind stuff, as the cow was. We have then that not only the thoughts are made of mind stuff, but also the *self* itself seems to be made of it.

If we reproduce exactly the functioning of the human brain when performing a certain task, such as tasting a wine, would the resulting machine be able to actually *appreciate* the wine? Such is the vision of *functionalism*. It wouldn't matter if the *thinker* is made of brain stuff or silicon, if the processes that happens in it are the same. It is hard to believe that a machine would be able to *appreciate* it, but isn't the brain a machine of sorts, with its mechanical explanation? It may seem compelling then that it is not the brain which does the appreciating: it is *the mind* which does it, and reproduction of the brain machinery wouldn't yield real appreciation.

So we may say that the mind is not only where thoughts and perceptions happen, but also where the *appreciating* takes place. Somehow he follows (this all seems pretty messy to me): maybe it is where appreciation happens because it is also the source of our intentional actions. If doing things that matter depends on our consciousness, then *mattering* things must depend as well on consciousness. When we account someone responsible for something, it is becouse that person was *conscious* of it. When we perform a certain action it is, somehow, triggered by our conscious mind, by a *real me*, which cannot just be the brain or any part of it, since no part of the brain could:

- be the medium in which we render the purple cow
- be the thinking thing
- appreciate, hate, love, *matter*
- act with moral responsibility

*** 4. WHY DUALISM IS FORLORN

The pervious idea of the mind separated from the brain is *dualism*, largely discarded today and replaced by *materialism*: there is only *matter*, and the mind is nothing else than a physical phenomenon.

What is so wrong with dualism? It basically states that at some part of the brain (the pineal gland, according to Descartes), the mind receives information from the brain and issues commands to it. However, since the brain is a physical system, whatever interacts with it must be a physical system as well, even if it is some kind of physical entity which we do not understand yet. Something like that is proposed by Roger Penrose in *The Emperor's New Mind*.

Dualists insist that mind is beyond human ken, and Dennet considers this the most disqualifying feature of it. Even if we cannot fully disprove dualism, *accepting it means giving up*.

Even if materialism is widely accepted, overcoming the traditional views of dualism is hard and counterintuitive, and so is the theory proposed by Dennet.

Some brain researchers study the brain as another organ, never trying to mention the mind or anything "mental". For others, more theoretically inclined, the mind is a new field of study. But even these try to postpone the questions about the nature of consciousness.

Efforts to understand the brain have adopted a divide-and-conquer strategy. While this is a legitimate and useful approach, it also has the effect of distorting some of the concepts which arise from the study. We tend to study the peripheral systems of the mind/brain as rather isolated systems which feed some kind of decision center where conscious thought and experience happen. This central arena is thought as well to avail itself of material held in subservient systems of memory. **But this idea of division between this subservient systems and the center of the brain, (the thinking thing, what Dennet calls a "Cartesian Theater") is more of an artifact of the divide-an-conquer strategy than anything found in nature.**

*** 5. THE CHALLENGE

Dennet establishes in this chapter some rules for his project of formulating a theory of consciousness, which are the following:

- *No Wonder Tissue allowed*: he will not propose new forces or substances external to the current understanding of physics.
- *No feigning anesthesia*: if he denies the existence of some feature of consciousness, it relies upon him to prove it.
- *No nitpicking about empirical details*: he will try to get all the scientific facts right, but he will take into account theories and discoveries which have not been definitely accepted. He justifies this saying that without some of them, he would not avail himself of some of the most eye-opening advances.

He will, using these rules, try to get to theory sketches, not to established and empirically confirmed  theories. These sketches of how the mind might work can open new lines of research, which might in turn refute the theories or modify them, but at least in this way we have a starting point.

Along this chapter we have seen which are the basic features of the mystery of consciousness. We have as well seen why dualism should be discarded, since it would mean abandoning any attempts to explain consciousness. The mind must be the brain, but materialism doesn't guaranty solving the puzzle of consciousness, it only promises to explain it some day. In order to do so, we must abandon more of Descartes's legacy. Also, we must not neglect the facts about experience that we know "from the inside".
